# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_studentbadges_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregisteredcourses',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course'),
        ),
    ]
