# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_auto_20160921_2109'),
        ('Students', '0012_auto_20160923_1531'),
    ]

    operations = [
    ]
