# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0014_leaderboards_studentconfigparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avaterImage',
            field=models.CharField(default='', max_length=200),
        ),
    ]
