# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-16 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0015_student_avatarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbadges',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
