# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0017_merge_20161117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='courseBucks',
            field=models.IntegerField(default=0),
        ),
    ]
