# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0018_studentconfigparams_coursebucks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAvatarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarImage', models.FileField(max_length=500, upload_to='/home/jevans116/workspace/oneUp/media/images/uploadedAvatarImages')),
                ('avatarImageFileName', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
