# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_uploadedavatarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='D:\\workspace\\oneUp\\media\\images/uploadedAvatarImages'),
        ),
    ]
