# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_auto_20170225_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='/home/jevans116/workspace/oneUp/media/images/uploadedAvatarImages'),
        ),
    ]
