# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0038_auto_20170228_1500'),
        ('Students', '0022_auto_20170227_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentactivities',
            old_name='studentActivityAssignmentID',
            new_name='studentActivityID',
        ),
        migrations.AddField(
            model_name='studentactivities',
            name='courseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='D:\\workspace\\oneUp\\media\\images/uploadedAvatarImages'),
        ),
    ]
