# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0023_auto_20170228_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='C:\\Users\\austin\\Documents\\Workspaces\\oneUp\\media\\images/uploadedAvatarImages'),
        ),
    ]
