# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0018_auto_20170322_1934'),
        ('Students', '0024_auto_20170322_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVirtualCurrency',
            fields=[
                ('studentVcID', models.AutoField(primary_key=True, serialize=False)),
                ('objectID', models.IntegerField(default=-1, verbose_name='index into the appropriate table')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
                ('vcRuleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.VirtualCurrencyRuleInfo', verbose_name='the virtual currency rule')),
            ],
        ),
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='virtualCurrencyAmount',
            field=models.IntegerField(default=0),
        ),
    ]
