# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0026_auto_20170324_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='/home/kirwin/workspace/oneUp-SVN/media/images/uploadedAvatarImages'),
        ),
    ]
