# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0027_auto_20170404_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatarImage',
        ),
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='avatarImage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='D:\\workspace\\oneUpER\\media\\images/uploadedAvatarImages'),
        ),
    ]
