# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0031_auto_20170413_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='/home/dichevc/workspace/oneUpER/media/images/uploadedAvatarImages'),
        ),
    ]
