# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0033_auto_20170423_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='/Users/intgeni/WSSU/Fall2016/oneUp_Project_backups/git_oneUp/media/images/uploadedAvatarImages'),
        ),
    ]
