# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0033_auto_20170423_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedavatarimage',
            name='avatarImage',
            field=models.FileField(max_length=500, upload_to='/home/jevans116/workspace/oneUpGit/media/images/uploadedAvatarImages'),
        ),
    ]
