# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0034_auto_20170523_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchallengequestions',
            name='seed',
            field=models.IntegerField(default=0),
        ),
    ]
