# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0057_auto_20170819_2135'),
        ('Students', '0035_studentchallengequestions_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('studentFileID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='instructorFeedback',
            field=models.CharField(default='No feedback yet ', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 14, 52, 11, 342255)),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.StudentActivities', verbose_name='the related activity'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.UploadedFiles', verbose_name='the related file to the student'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student'),
        ),
    ]
