# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0037_auto_20170831_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 15, 12, 53, 102243)),
        ),
    ]
