# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 19:04
from __future__ import unicode_literals

import Students.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0039_auto_20170831_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='fileName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 19, 4, 7, 194594)),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=Students.models.fileUploadPath),
        ),
    ]
