# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-06 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0040_auto_20170831_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 4, 41, 18, 98628)),
        ),
    ]
