# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0036_remove_student_avaterimage'),
        ('Students', '0040_auto_20170831_1904'),
    ]

    operations = [
    ]
