# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0042_auto_20170914_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 17, 50, 23, 857184)),
        ),
    ]
