# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0063_delete_difficulty'),
        ('Students', '0042_auto_20171002_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaderboardHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaderboardPosition', models.IntegerField(default=0)),
                ('startTimestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Start Timestamp')),
                ('endTimestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='End Timestamp')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='studentID',
        ),
        migrations.DeleteModel(
            name='Leaderboards',
        ),
    ]
