# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0043_auto_20171015_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleaderboardhistory',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End Timestamp'),
        ),
    ]
