# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0063_delete_difficulty'),
        ('Students', '0044_auto_20171015_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVirtualCurrencyTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectType', models.IntegerField(verbose_name='which type of object is involved, for example, challenge, individual question, or other activity.  Should be a reference to an objectType Enum')),
                ('objectID', models.IntegerField(verbose_name='index into the appropriate table')),
                ('status', models.CharField(default='Requested', max_length=200)),
                ('noteForStudent', models.CharField(max_length=300)),
                ('instructorNote', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course in Which event occurred')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
                ('studentEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.StudentEventLog', verbose_name='the Student Event Log')),
            ],
        ),
    ]
