# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-09 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0045_auto_20171103_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
