# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-03 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0045_studentvirtualcurrencytransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvirtualcurrencytransactions',
            name='id',
        ),
        migrations.AddField(
            model_name='studentvirtualcurrencytransactions',
            name='transactionID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
