# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0046_studentactivities_graded'),
        ('Students', '0047_auto_20171110_2120'),
    ]

    operations = [
    ]
