# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0048_merge_20171115_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='numOfUploads',
            field=models.IntegerField(default=1),
        ),
    ]
