# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0049_studentactivities_numofuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='numOfUploads',
            field=models.IntegerField(default=0),
        ),
    ]
