# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0051_auto_20171117_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconfigparams',
            name='displayBadges',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentconfigparams',
            name='displayClassAverage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentconfigparams',
            name='displayClassRanking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentconfigparams',
            name='displayClassSkills',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentconfigparams',
            name='displayLeaderBoard',
            field=models.BooleanField(default=True),
        ),
    ]
