# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-19 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0053_auto_20180118_2020'),
        ('Students', '0053_auto_20180119_1939'),
    ]

    operations = [
    ]
