# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0054_merge_20180119_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvirtualcurrency',
            name='value',
            field=models.IntegerField(default=0, verbose_name='The amount that was given to the student'),
        ),
    ]
