# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0055_studentvirtualcurrency_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteventlog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='Course in Which event occurred'),
        ),
        migrations.AlterField(
            model_name='studenteventlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.Student', verbose_name='the student'),
        ),
    ]
