# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0056_auto_20180123_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentchallenges',
            name='testTotal',
        ),
        migrations.AddField(
            model_name='studentchallenges',
            name='scoreAdjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
