# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0057_auto_20180209_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchallenges',
            name='adjustmentReason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
