# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0058_studentchallenges_adjustmentreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='bonusPointsAwarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='studentchallenges',
            name='bonusPointsAwarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
