# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0059_auto_20180321_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvirtualcurrencytransactions',
            name='instructorNote',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='studentvirtualcurrencytransactions',
            name='noteForStudent',
            field=models.CharField(max_length=600),
        ),
    ]
