# Generated by Django 2.0.8 on 2018-08-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0061_auto_20180817_0008'),
        ('Badges', '0038_badgesinfo')
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbadges',
            name='badgeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.BadgesInfo', verbose_name='the badge'),
        ),
    ]
