# Generated by Django 2.0.8 on 2018-08-22 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0088_auto_20180817_1639'),
        ('Students', '0062_auto_20180817_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('studentAttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('isPresent', models.BooleanField(default=False)),
                ('courseID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
