# Generated by Django 2.0.8 on 2018-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0063_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isTestStudent',
            field=models.BooleanField(default=False),
        ),
    ]
