# Generated by Django 2.0.8 on 2018-11-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0060_progressiveunlocking'),
        ('Students', '0064_student_isteststudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressiveUnlocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField(default=-1, verbose_name='index into the appropriate table')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isFullfilled', models.BooleanField(default=False, verbose_name='Did the student fullfill the unlocking rule')),
                ('pUnlockingRuleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.VirtualCurrencyCustomRuleInfo', verbose_name='the progressive unlocking rule')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
            ],
        ),
    ]
