# Generated by Django 2.0.8 on 2018-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0064_student_isteststudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
