# Generated by Django 2.0.8 on 2018-09-25 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0065_studentactivities_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='submissionTimestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
