# Generated by Django 2.0.8 on 2018-11-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0065_studentprogressiveunlocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressiveunlocking',
            name='objectType',
            field=models.IntegerField(db_index=True, default=1301, verbose_name='which type of object is involved, for example, challenge, individual question, or other activity.  Should be a reference to an objectType Enum'),
        ),
    ]
