# Generated by Django 2.0.8 on 2018-11-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0088_auto_20180817_1639'),
        ('Students', '0066_studentactivities_submissiontimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelChallenges',
            fields=[
                ('duelChallengeID', models.AutoField(primary_key=True, serialize=False)),
                ('duelChallengeName', models.CharField(max_length=100)),
                ('isBetting', models.BooleanField(default=False)),
                ('vcBet', models.IntegerField(default=0)),
                ('sendTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Start Timestamp')),
                ('startTime', models.IntegerField(default=1440)),
                ('timeLimit', models.IntegerField(default=120)),
                ('customMessage', models.CharField(default='', max_length=600)),
                ('status', models.IntegerField(default=1)),
                ('hasStarted', models.BooleanField(default=False)),
                ('hasEnded', models.BooleanField(default=False)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Challenges', verbose_name='the related challenge')),
                ('challengee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengee', to='Students.Student', verbose_name='the related student')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='Students.Student', verbose_name='the related student')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DuelChallengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.DuelChallenges', verbose_name='the related Duel')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
