# Generated by Django 2.0.8 on 2018-10-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0065_auto_20181018_1756'),
        ('Students', '0066_studentactivities_submissiontimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicallyUpdatedleaderboards',
            fields=[
                ('periodicLeaderboardID', models.AutoField(primary_key=True, serialize=False)),
                ('studentPoints', models.IntegerField(default=0)),
                ('studentPosition', models.IntegerField(default=0)),
                ('leaderboardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.LeaderboardsConfig', verbose_name='the related leaderboard configuration object')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
