# Generated by Django 2.0.8 on 2019-02-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0067_duelchallenges_winners'),
        ('Students', '0067_auto_20181102_0136'),
    ]

    operations = [
    ]
