# Generated by Django 2.0.8 on 2018-11-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0088_auto_20180817_1639'),
        ('Students', '0067_auto_20181102_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressiveunlocking',
            name='courseID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name'),
            preserve_default=False,
        ),
    ]
