# Generated by Django 2.0.8 on 2018-12-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0068_auto_20181207_0022'),
        ('Students', '0068_studentprogressiveunlocking_courseid'),
    ]

    operations = [
    ]
