# Generated by Django 2.0.8 on 2018-12-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0067_periodicallyupdatedleaderboards'),
        ('Students', '0068_auto_20181207_0022'),
    ]

    operations = [
    ]
