# Generated by Django 2.0.8 on 2019-01-11 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0068_auto_20181207_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='attendanceStreakStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
