# Generated by Django 2.0.8 on 2019-01-11 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0069_studentregisteredcourses_attendancestreakstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregisteredcourses',
            name='attendanceStreakStartDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
