# Generated by Django 2.0.8 on 2019-02-05 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0091_auto_20181218_1444'),
        ('Students', '0069_merge_20181221_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStreaks',
            fields=[
                ('studentStreakID', models.AutoField(primary_key=True, serialize=False)),
                ('streakStartDate', models.DateTimeField(blank=True, null=True, verbose_name='The date the streak reset on')),
                ('streakType', models.IntegerField(default=0)),
                ('objectID', models.IntegerField(default=0)),
                ('currentStudentStreakLength', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentactivities',
            name='submissionTimestamp',
        ),
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='attendanceStreakStartDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Grading Timestamp'),
        ),
    ]
