# Generated by Django 2.0.8 on 2018-12-21 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0069_merge_20181221_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivities',
            name='submissionTimestamp',
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Grading Timestamp'),
        ),
    ]
