# Generated by Django 2.0.8 on 2019-01-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0069_merge_20181217_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivities',
            name='submissionTimestamp',
        ),
    ]
