# Generated by Django 2.0.8 on 2019-02-04 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
        ('Students', '0070_auto_20181221_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStreaks',
            fields=[
                ('studentStreakID', models.AutoField(primary_key=True, serialize=False)),
                ('streakStartDate', models.DateTimeField(blank=True, null=True, verbose_name='The date the streak reset on')),
                ('streakType', models.IntegerField(default=0)),
                ('objectID', models.IntegerField(default=0)),
                ('currentStudentStreakLength', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='attendanceStreakStartDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
