# Generated by Django 2.0.8 on 2019-02-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0069_merge_20181217_1253'),
        ('Students', '0070_auto_20181221_1715'),
    ]

    operations = [
    ]
