# Generated by Django 2.0.8 on 2019-01-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0070_auto_20181221_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='participateInDuel',
            field=models.BooleanField(default=True),
        ),
    ]
