# Generated by Django 2.1.2 on 2019-02-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0069_courseconfigparams_chatused'),
        ('Students', '0071_studentconfigparams_participateinduel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoalSetting',
            fields=[
                ('studentGoalID', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.IntegerField(db_index=True, default=0, verbose_name='The goal set by the student. Should be a reference to the Goal enum')),
                ('objectID', models.IntegerField(default=-1, verbose_name='index into the appropriate table')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('targetedNumber', models.IntegerField(default=0, verbose_name='A number related to the goal.')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
                ('vcRuleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.VirtualCurrencyCustomRuleInfo', verbose_name='the virtual currency rule')),
            ],
        ),
    ]
