# Generated by Django 2.0.8 on 2019-02-04 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0091_auto_20181218_1444'),
        ('Badges', '0068_merge_20190128_1553'),
        ('Students', '0071_studentconfigparams_participateinduel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvirtualcurrency',
            name='vcRuleID',
        ),
        migrations.CreateModel(
            name='StudentVirtualCurrencyRuleBased',
            fields=[
                ('studentvirtualcurrency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Students.StudentVirtualCurrency')),
                ('vcRuleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Badges.VirtualCurrencyCustomRuleInfo', verbose_name='the virtual currency rule')),
            ],
            bases=('Students.studentvirtualcurrency',),
        ),
        migrations.AddField(
            model_name='studentvirtualcurrency',
            name='courseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the course'),
        ),
        migrations.AddField(
            model_name='studentvirtualcurrency',
            name='vcDescription',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='studentvirtualcurrency',
            name='vcName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
