# Generated by Django 2.0.8 on 2019-01-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0071_studentstreaks'),
        ('Students', '0070_auto_20181221_1715'),
    ]

    operations = [
    ]
