# Generated by Django 2.0.8 on 2019-02-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0072_auto_20190204_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvirtualcurrencyrulebased',
            name='vcRuleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcrule', to='Badges.VirtualCurrencyCustomRuleInfo', verbose_name='the virtual currency rule'),
        ),
    ]
