# Generated by Django 2.0.8 on 2019-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0072_merge_20190119_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstreaks',
            old_name='completedStreakCount',
            new_name='currentStudentStreakLength',
        ),
        migrations.AddField(
            model_name='studentstreaks',
            name='objectID',
            field=models.IntegerField(default=0),
        ),
    ]
