# Generated by Django 2.0.8 on 2019-02-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0072_auto_20190201_1719'),
        ('Students', '0071_auto_20190204_1452'),
    ]

    operations = [
    ]
