# Generated by Django 2.0.8 on 2019-02-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0073_merge_20190204_1513'),
        ('Students', '0073_auto_20190204_1925'),
    ]

    operations = [
    ]
