# Generated by Django 2.0.8 on 2019-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0073_auto_20190125_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstreaks',
            name='id',
        ),
        migrations.AddField(
            model_name='studentstreaks',
            name='studentStreakID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
