# Generated by Django 2.1.2 on 2019-02-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0074_merge_20190205_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvirtualcurrencyrulebased',
            name='vcRuleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcrule', to='Badges.VirtualCurrencyCustomRuleInfo', verbose_name='the virtual currency rule'),
        ),
    ]
