# Generated by Django 2.1.2 on 2019-02-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0073_merge_20190208_1555'),
        ('Students', '0075_auto_20190208_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicallyUpdatedleaderboards',
            fields=[
                ('periodicLeaderboardID', models.AutoField(primary_key=True, serialize=False)),
                ('studentPoints', models.IntegerField(default=0)),
                ('studentPosition', models.IntegerField(default=0)),
                ('leaderboardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.LeaderboardsConfig', verbose_name='the related leaderboard configuration object')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
