# Generated by Django 2.1.2 on 2019-02-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0072_studentgoalsetting'),
        ('Students', '0075_auto_20190208_1544'),
    ]

    operations = [
    ]
