# Generated by Django 2.1.2 on 2019-03-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0076_periodicallyupdatedleaderboards'),
        ('Students', '0072_studentgoalsetting'),
    ]

    operations = [
    ]
