# Generated by Django 2.1.2 on 2019-03-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
        ('Students', '0077_merge_20190306_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgoalsetting',
            old_name='goal',
            new_name='goalType',
        ),
        migrations.AddField(
            model_name='studentgoalsetting',
            name='courseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the course'),
        ),
    ]
