# Generated by Django 2.0.8 on 2019-04-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
        ('Students', '0079_auto_20190307_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalloutParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSubmitted', models.BooleanField(default=False)),
                ('hasWon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Callouts',
            fields=[
                ('calloutID', models.AutoField(primary_key=True, serialize=False)),
                ('sendTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Send Timestamp')),
                ('endTime', models.DateTimeField(db_index=True, verbose_name='End Time')),
                ('customMessage', models.CharField(default='', max_length=6000)),
                ('hasEnded', models.BooleanField(default=False)),
                ('isIndividual', models.BooleanField()),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Challenges', verbose_name='the related challenge')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Students.Student', verbose_name='the related student')),
            ],
        ),
        migrations.AddField(
            model_name='calloutparticipants',
            name='calloutID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Callouts', verbose_name='the related Callout'),
        ),
        migrations.AddField(
            model_name='calloutparticipants',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course'),
        ),
        migrations.AddField(
            model_name='calloutparticipants',
            name='participantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student'),
        ),
    ]
