# Generated by Django 2.1.2 on 2019-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0079_auto_20190307_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgoalsetting',
            name='progressToGoal',
            field=models.IntegerField(default=0, verbose_name='A percentage of the students progress towards the goal.'),
        ),
    ]
