# Generated by Django 2.1.2 on 2019-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0080_studentgoalsetting_progresstogoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='displayGoal',
            field=models.BooleanField(default=True),
        ),
    ]
