# Generated by Django 2.0.8 on 2019-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0080_auto_20190402_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='participateInCallout',
            field=models.BooleanField(default=True),
        ),
    ]
