# Generated by Django 2.0.8 on 2019-04-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
        ('Students', '0081_studentconfigparams_participateincallout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalloutStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calloutVC', models.IntegerField()),
                ('submitTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Send Timestamp')),
                ('calloutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Callouts', verbose_name='the related Callout')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('studentChallenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.StudentChallenges', verbose_name='the related student challenge')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
