# Generated by Django 2.0.8 on 2019-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0081_studentconfigparams_displaygoal'),
        ('Students', '0082_calloutstats'),
    ]

    operations = [
    ]
