# Generated by Django 2.1.2 on 2019-05-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0084_remove_studentconfigparams_displaygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='displayGoal',
            field=models.BooleanField(default=True),
        ),
    ]
