# Generated by Django 2.1.2 on 2019-05-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0084_auto_20190510_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfigparams',
            name='displayGoal',
            field=models.BooleanField(default=True),
        ),
    ]
