# Generated by Django 2.1.2 on 2019-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0085_studentconfigparams_displaygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgoalsetting',
            name='recurringGoal',
            field=models.BooleanField(default=True),
        ),
    ]
