# Generated by Django 2.2.4 on 2019-08-22 19:09

from django.db import migrations, models
from django.db.models import F
from Badges.enums import Event

def migrate_student_transactions(apps, schema_editor):
    # Update the old student transactions by copying the related rule info into the newly created model fields
    # Doing this will preserve the history of these transactions
    StudentVirtualCurrencyTransactions = apps.get_model("Students","StudentVirtualCurrencyTransactions")
    VirtualCurrencyCustomRuleInfo = apps.get_model("Badges","VirtualCurrencyCustomRuleInfo")
    transactions = StudentVirtualCurrencyTransactions.objects.filter(studentEvent__event=Event.spendingVirtualCurrency)
    for transaction in transactions:
        rule = VirtualCurrencyCustomRuleInfo.objects.filter(vcRuleType=False, vcRuleID=transaction.studentEvent.objectID).first()
        if rule:
            transaction.name = rule.vcRuleName
            transaction.description = rule.vcRuleDescription
            transaction.amount = rule.vcRuleAmount
            transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0085_studentconfigparams_displaygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvirtualcurrencytransactions',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='The amount of the transaction (usually the vcAmount a rule'),
        ),
        migrations.AddField(
            model_name='studentvirtualcurrencytransactions',
            name='description',
            field=models.CharField(default='', max_length=4000, verbose_name='The description of the transaction (usually the vcDescription a rule'),
        ),
        migrations.AddField(
            model_name='studentvirtualcurrencytransactions',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='The name of the transaction (usually the vcRuleName a rule'),
        ),
        migrations.RunPython(migrate_student_transactions),
    ]
