# Generated by Django 2.0.8 on 2019-10-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0086_auto_20190822_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelchallenges',
            name='evaluator',
            field=models.IntegerField(default=0),
        ),
    ]
