# Generated by Django 2.2.4 on 2019-11-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0088_auto_20191024_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActions',
            fields=[
                ('studentActionsID', models.AutoField(primary_key=True, serialize=False)),
                ('json_data', models.TextField(blank=True, default='{}', help_text='JSON encoded table of student results', verbose_name='Student JSON Results')),
                ('warmups_attempted', models.IntegerField(default=0, verbose_name='# of Warmups Attempted')),
                ('serious_attempted', models.IntegerField(default=0, verbose_name='# of Serious Challenges Attempted')),
                ('duels_sent', models.IntegerField(default=0, verbose_name='# of Duels Sent')),
                ('duels_accepted', models.IntegerField(default=0, verbose_name='# of Duels Accepted')),
                ('callouts_sent', models.IntegerField(default=0, verbose_name='# of Callouts Accpeted')),
                ('callouts_accepted', models.IntegerField(default=0, verbose_name='# of Callouts Sent')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Created Timestamp')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
            ],
        ),
    ]
