# Generated by Django 2.0.8 on 2020-01-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0090_studentchallengequestions_challengequestionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelchallenges',
            name='hasExpired',
            field=models.BooleanField(default=False),
        ),
    ]
