# Generated by Django 2.2.5 on 2020-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0092_auto_20200130_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchallengeanswers',
            name='studentAnswer',
            field=models.CharField(max_length=10000),
        ),
    ]
