# Generated by Django 2.2.4 on 2020-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0095_auto_20200302_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='displayDarkMode',
            field=models.BooleanField(default=False),
        ),
    ]
