# Generated by Django 2.2.5 on 2020-04-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0096_student_displaydarkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchallengequestions',
            name='usedHint',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentAnswerHints',
            fields=[
                ('studentAnswerHintsID', models.AutoField(primary_key=True, serialize=False)),
                ('challengeQuestionID', models.IntegerField(default=0)),
                ('usedBasicHint', models.BooleanField(default=False)),
                ('usedStrongHint', models.BooleanField(default=False)),
                ('studentChallengeQuestionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.StudentChallengeQuestions', verbose_name='the related student_challenge_question hint')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
    ]
