# Generated by Django 2.2.4 on 2020-04-04 05:35

from django.db import migrations, models
import django.utils.timezone
import datetime

def migrate_student_dates(apps, schema_editor):
    # Update the course config "has date" parameters 

    StudentActivities = apps.get_model("Students","StudentActivities")

    default_date_year = datetime.datetime.strptime("12/31/2999 11:59 PM", "%m/%d/%Y %I:%M %p").replace(tzinfo=datetime.timezone.utc).year
    
    student_activities = StudentActivities.objects.all()
    for params in student_activities:
        save = False
        # This datetimefield is assume to not be a default datetime since the year is < 2999
        if params.timestamp.year < default_date_year:
            params.hasTimestamp = True
            save = True

        if save:
            params.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0096_student_displaydarkmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='hasTimestamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callouts',
            name='endTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='callouts',
            name='sendTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='calloutstats',
            name='submitTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='duelchallenges',
            name='acceptTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Accept Timestamp'),
        ),
        migrations.AlterField(
            model_name='duelchallenges',
            name='sendTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentchallenges',
            name='endTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentchallenges',
            name='startTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studenteventlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='studentleaderboardhistory',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='End Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentleaderboardhistory',
            name='startTimestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Start Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentprogressiveunlocking',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentstreaks',
            name='streakStartDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='The date the streak reset on'),
        ),
        migrations.AlterField(
            model_name='studentvirtualcurrency',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentvirtualcurrencytransactions',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='timestamp'),
        ),
        migrations.RunPython(migrate_student_dates),
    ]
