# Generated by Django 2.1.2 on 2020-04-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0097_setup_default_dates'),
        ('Students', '0097_auto_20200406_1532'),
    ]

    operations = [
    ]
