# Generated by Django 2.2.4 on 2020-04-20 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0123_delete_coursessubtopics'),
        ('Students', '0099_studentregisteredcourses_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentFlashCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyDate', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='the ideal date the flash card should reappear')),
                ('cardBin', models.IntegerField(db_index=True, default=0, verbose_name='priority containers for flash cards')),
                ('timesSeen', models.IntegerField(default=0, verbose_name='times the student has seen the card')),
                ('timesCorrect', models.IntegerField(default=0, verbose_name='times the student has correctly answered the card')),
                ('flashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.FlashCards', verbose_name='the flash card')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the student')),
            ],
        ),
    ]
