# Generated by Django 2.2.4 on 2020-04-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0107_auto_20200415_1646'),
        ('Students', '0100_studentflashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgoalsetting',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Indicates whether the goal is completed and no longer has a rule associated with it'),
        ),
        migrations.AddField(
            model_name='studentgoalsetting',
            name='ruleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the goal rule'),
        ),
    ]
