# Generated by Django 2.2.4 on 2020-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0102_auto_20200421_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgoalsetting',
            name='targetedNumber',
            field=models.FloatField(default=0, verbose_name='A number related to the goal.'),
        ),
    ]
