# Generated by Django 2.2.4 on 2020-04-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0103_auto_20200421_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgoalsetting',
            name='progressToGoal',
            field=models.FloatField(default=0, verbose_name='A percentage of the students progress towards the goal.'),
        ),
    ]
