# Generated by Django 2.2.4 on 2020-04-29 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0104_auto_20200421_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='submissionTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Latest submission timestamp'),
        ),
        migrations.AddField(
            model_name='studentactivities',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='instructorFeedback',
            field=models.CharField(default='', max_length=200),
        ),
    ]
