# Generated by Django 2.2.4 on 2020-07-08 17:26

import Students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0105_auto_20200428_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callouts',
            name='endTime',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='callouts',
            name='sendTime',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='calloutstats',
            name='submitTime',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='duelchallenges',
            name='acceptTime',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='Accept Timestamp'),
        ),
        migrations.AlterField(
            model_name='duelchallenges',
            name='sendTime',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='submissionTimestamp',
            field=models.DateTimeField(default=Students.models.custom_now, verbose_name='Latest submission timestamp'),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now, verbose_name='Grading Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentbadges',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentchallenges',
            name='endTimestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentchallenges',
            name='startTimestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studenteventlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentflashcards',
            name='studyDate',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='the ideal date the flash card should reappear'),
        ),
        migrations.AlterField(
            model_name='studentgoalsetting',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentleaderboardhistory',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=Students.models.custom_now, null=True, verbose_name='End Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentleaderboardhistory',
            name='startTimestamp',
            field=models.DateTimeField(db_index=True, default=Students.models.custom_now, verbose_name='Start Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentprogressiveunlocking',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentregisteredcourses',
            name='attendanceStreakStartDate',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentstreaks',
            name='streakStartDate',
            field=models.DateTimeField(blank=True, default=Students.models.custom_now, null=True, verbose_name='The date the streak reset on'),
        ),
        migrations.AlterField(
            model_name='studentvirtualcurrency',
            name='timestamp',
            field=models.DateTimeField(default=Students.models.custom_now),
        ),
        migrations.AlterField(
            model_name='studentvirtualcurrencytransactions',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=Students.models.custom_now, null=True, verbose_name='timestamp'),
        ),
    ]
