# Generated by Django 2.2.4 on 2020-11-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0107_teamactivities_teamchallengequestions_teamchallenges_teams_teamstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name="the team's leader"),
        ),
    ]
