# Generated by Django 2.2.4 on 2020-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0108_auto_20201109_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='activeTeam',
            field=models.BooleanField(default=True, verbose_name='Indicates whether or not team is in current set of active teams'),
        ),
        migrations.AddField(
            model_name='teamstudents',
            name='activeMember',
            field=models.BooleanField(default=True, verbose_name='Indicates whether student is currently an active member of team'),
        ),
    ]
