# Generated by Django 2.2.4 on 2020-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0109_auto_20201207_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstudents',
            name='modeOfEnrollment',
            field=models.CharField(default='', max_length=1),
        ),
    ]
