# Generated by Django 2.1.15 on 2021-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0110_teamstudents_modeofenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivities',
            name='instructorFeedback',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
