# Generated by Django 2.2.4 on 2021-05-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0111_auto_20210430_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChallengeAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamAnswer', models.CharField(max_length=10000)),
                ('teamChallengeQuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.TeamChallengeQuestions', verbose_name='the related team_challenge_question')),
            ],
        ),
    ]
