# Generated by Django 2.1.15 on 2021-07-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0112_teamchallengeanswers'),
        ('Students', '0112_studentplayertype'),
    ]

    operations = [
    ]
