# Generated by Django 2.1.2 on 2021-09-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0113_merge_20210703_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregisteredcourses',
            name='donationAmount',
            field=models.IntegerField(default=0),
        ),
    ]
