# Generated by Django 2.1.2 on 2022-01-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0114_studentregisteredcourses_donationamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceIndex', models.IntegerField(default=1)),
                ('noseIndex', models.IntegerField(default=1)),
                ('mouthIndex', models.IntegerField(default=1)),
                ('eyeIndex', models.IntegerField(default=1)),
                ('eyebrowIndex', models.IntegerField(default=1)),
                ('eyewearIndex', models.IntegerField(default=0)),
                ('hairIndex', models.IntegerField(default=1)),
                ('fahairIndex', models.IntegerField(default=0)),
                ('clothesIndex', models.IntegerField(default=1)),
                ('backgroundIndex', models.IntegerField(default=1)),
                ('faceColorIndex', models.IntegerField(default=1)),
                ('eyeColorIndex', models.IntegerField(default=1)),
                ('eyebrowColorIndex', models.IntegerField(default=1)),
                ('eyewearColorIndex', models.IntegerField(default=1)),
                ('hairColorIndex', models.IntegerField(default=1)),
                ('fahairColorIndex', models.IntegerField(default=1)),
                ('clothesColorIndex', models.IntegerField(default=1)),
                ('backgroundColorIndex', models.IntegerField(default=1)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student', verbose_name='the related student')),
            ],
        ),
        migrations.AddField(
            model_name='studentactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='teamactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
