# Generated by Django 2.1.2 on 2022-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0116_auto_20220110_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcustomavatar',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
