# Generated by Django 2.1.2 on 2022-02-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0117_studentcustomavatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcustomavatar',
            name='image',
            field=models.CharField(default='default_profilePicture.png', max_length=200),
        ),
    ]
