# Generated by Django 2.1.2 on 2022-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0118_auto_20220201_2007'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='studentcustomavatar',
            name='image',
            field=models.CharField(default='/static/images/generatedAvatarImages/default_profilePicture.png', max_length=200),
        ),
    ]
