# Generated by Django 2.1.2 on 2021-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0114_studentregisteredcourses_donationamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='teamactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
