# Generated by Django 2.1.2 on 2021-10-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     
 
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='studentflashcards',
            name='courseID',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamactivities',
            name='richTextSubmission',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
