# Generated by Django 2.1.2 on 2021-10-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       
        ('Students', '0115_auto_20211025_0034'),
    ]

    operations = [
    ]
