# Generated by Django 2.1.2 on 2021-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0116_merge_20211028_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentflashcards',
            name='courseID',
        ),
    ]
