# Generated by Django 2.0.8 on 2019-12-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0088_studentactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelchallenges',
            name='hasExpired',
            field=models.BooleanField(default=False),
        ),
    ]
