# Generated by Django 2.0.8 on 2018-11-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0001_initial'),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='course',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course'),
            preserve_default=False,
        ),
    ]
