# Generated by Django 2.0.8 on 2019-01-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20190122_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_course',
            new_name='course',
        ),
    ]
