# Generated by Django 2.0.8 on 2019-01-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0091_auto_20181218_1444'),
        ('Chat', '0003_auto_20190122_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_url',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('channel_name', 'course', 'channel_url')},
        ),
    ]
