# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0010_auto_20151209_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='feedbackOption',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='numberAttempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='timeLimit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challengesquestions',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courseconfigparams',
            name='courseBucks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionsskills',
            name='questionSkillPoints',
            field=models.IntegerField(default=1),
        ),
    ]
