# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0012_challenges_isvisable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='isVisable',
            new_name='isVisible',
        ),
    ]
