# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0014_auto_20160331_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
