# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0015_auto_20160331_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='endTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 21, 55, 40, 192006, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='startTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 21, 56, 11, 366475, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
