# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challengePassword',
            field=models.CharField(default=datetime.datetime(2016, 4, 27, 3, 52, 54, 509426, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
