# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0018_challenges_challengepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='feedbackOption',
            field=models.CharField(max_length=10),
        ),
    ]
