# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0020_auto_20160427_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseDescription',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
