# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0021_courses_coursedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='courseBucks',
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='isCourseBucksDisplayed',
            field=models.BooleanField(default=False),
        ),
    ]
