# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0026_auto_20161026_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='challengeCategory',
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challengePassword',
            field=models.CharField(default='', max_length=30),
        ),
    ]
