# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 18:38
from __future__ import unicode_literals

from django.db import migrations

def copy_type(apps, schema_editor):
    Questions = apps.get_model("Instructors","Questions")
    for question in Questions.objects.all():
        question.typeNum = question.type.pk
        question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0028_questions_typenum'),
    ]

    operations = [
        migrations.RunPython(copy_type)
    ]
