# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0029_auto_20161221_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='type',
        ),
    ]
