# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0030_remove_questions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='typeNum',
            new_name='type',
        ),
    ]
