# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0032_delete_questiontypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestions',
            name='numParts',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dynamicquestions',
            name='code',
            field=models.CharField(max_length=20000),
        ),
    ]
