# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instructors', '0033_auto_20170214_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('imageFile', models.FileField(max_length=500, upload_to='D:\\workspace\\oneUp\\media\\images/uploadedInstructorImages')),
                ('imageDescription', models.CharField(default='', max_length=200)),
                ('imageCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
