# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0036_auto_20170225_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDynamicQuestions',
            fields=[
                ('dynamicquestions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Instructors.DynamicQuestions')),
                ('templateText', models.CharField(max_length=20000)),
            ],
            bases=('Instructors.dynamicquestions',),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='/home/jevans116/workspace/oneUp/media/images/uploadedInstructorImages'),
        ),
    ]
