# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0038_auto_20170228_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedynamicquestions',
            name='setupCode',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
