# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0040_auto_20170322_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='C:\\Users\\austin\\Documents\\Workspaces\\oneUpER\\media\\images/uploadedInstructorImages'),
        ),
    ]
