# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0041_auto_20170324_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesSubTopics',
            fields=[
                ('subTopicID', models.AutoField(primary_key=True, serialize=False)),
                ('subTopicName', models.CharField(max_length=100)),
                ('subTopicPos', models.IntegerField(default=0)),
                ('thresholdXP', models.IntegerField(default=0)),
                ('thresholdSP', models.IntegerField(default=0)),
                ('displayDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='courses')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Topics', verbose_name='topic')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='/home/kirwin/workspace/oneUp-SVN/media/images/uploadedInstructorImages'),
        ),
    ]
