# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0042_auto_20170404_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='D:\\workspace\\oneUpER\\media\\images/uploadedInstructorImages'),
        ),
    ]
