# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0043_auto_20170405_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTextParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.IntegerField(default=1)),
                ('templateText', models.CharField(max_length=20000)),
                ('dynamicQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.TemplateDynamicQuestions')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='/home/kirwin/workspace/oneUp-SVN/media/images/uploadedInstructorImages'),
        ),
    ]
