# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0044_auto_20170407_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='/home/dichevc/workspace/oneUpER/media/images/uploadedInstructorImages'),
        ),
    ]
