# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0046_auto_20170413_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topicAuthor',
        ),
    ]
