# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instructors', '0049_auto_20170523_0012'),
    ]

    operations = [
    ]
