# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0050_auto_20170608_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lualibrary',
            name='libraryName',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
