# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0050_auto_20170503_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenentlibrary',
            name='dynamicQuestion',
        ),
        migrations.RemoveField(
            model_name='depenentlibrary',
            name='id',
        ),
        migrations.AddField(
            model_name='depenentlibrary',
            name='dependID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lualibrary',
            name='libFile',
            field=models.FileField(max_length=5000, upload_to='/home/jevans116/workspace/oneUpGit/media/lua/uploadedLuaLibs'),
        ),
    ]
