# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 03:38
from __future__ import unicode_literals

import Instructors.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0051_auto_20170609_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentlibrary',
            name='mainLibrary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainLibrary', to='Instructors.LuaLibrary'),
        ),
        migrations.AlterField(
            model_name='lualibrary',
            name='libFile',
            field=models.FileField(max_length=5000, upload_to=Instructors.models.luaLibraryUploadLocation),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to=Instructors.models.imageUploadPath),
        ),
    ]
