# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0050_auto_20170524_1543'),
        ('Instructors', '0052_auto_20170626_0338'),
    ]

    operations = [
    ]
