# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 00:24
from __future__ import unicode_literals

import Instructors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instructors', '0053_merge_20170626_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedFile', models.FileField(max_length=500, upload_to=Instructors.models.fileUploadPath)),
                ('uploadedFileName', models.CharField(default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploadedFileCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
