# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0054_uploadedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestopics',
            name='topicPos',
            field=models.IntegerField(default=0),
        ),
    ]
