# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0054_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinganswers',
            name='answerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Answers', verbose_name='the answer which this match goes with'),
        ),
    ]
