# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0055_auto_20170818_1848'),
        ('Instructors', '0055_coursestopics_topicpos'),
    ]

    operations = [
    ]
