# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0056_merge_20170818_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='activities',
            name='instructorNotes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='activities',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='subject',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challengeDifficulty',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='feedbackText',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goalsCol',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='milestones',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='promptText',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='correctAnswerFeedback',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='incorrectAnswerFeedback',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tagName',
            field=models.CharField(default='', max_length=75),
        ),
    ]
