# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0057_auto_20170819_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answerText',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='feedbackText',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='matchinganswers',
            name='matchingAnswerText',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='promptText',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
