# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0058_auto_20170903_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticquestions',
            name='correctAnswerFeedback',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='incorrectAnswerFeedback',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='questionText',
            field=models.CharField(max_length=10000),
        ),
    ]
