# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0059_auto_20170903_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='feedbackOption1',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='feedbackOption2',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='feedbackOption3',
        ),
        migrations.AddField(
            model_name='challenges',
            name='feedbackCorrectAnswer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='challenges',
            name='feedbackIncorrectAnswer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='challenges',
            name='instructorNotes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
