# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0060_auto_20170914_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='feedbackCorrectAnswer',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='feedbackIncorrectAnswer',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='instructorNotes',
        ),
        migrations.AddField(
            model_name='challenges',
            name='displayCorrectAnswer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='displayCorrectAnswerFeedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenges',
            name='displayIncorrectAnswerFeedback',
            field=models.BooleanField(default=False),
        ),
    ]
