# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0058_activities_isfileallowed'),
        ('Instructors', '0061_auto_20170914_2337'),
    ]

    operations = [
    ]
