# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0062_merge_20170919_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
