# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0063_delete_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesquestions',
            name='questionPosition',
            field=models.IntegerField(default=0),
        ),
    ]
