# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0064_challengesquestions_questionposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='timeLimit',
            field=models.IntegerField(verbose_name='time limit for the challenge in minutes'),
        ),
    ]
