# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0065_auto_20171103_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='uploadAttempts',
            field=models.IntegerField(default=1),
        ),
    ]
