# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0066_activities_uploadattempts'),
        ('Instructors', '0065_auto_20171103_2210'),
    ]

    operations = [
    ]
