# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-19 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0067_merge_20171115_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='endTimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='activities',
            name='startTimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
