# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-02 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0069_questionsskills_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsskills',
            name='challengeID',
        ),
    ]
