# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 07:47
from __future__ import unicode_literals

import Instructors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instructors', '0070_remove_questionsskills_challengeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedActivityFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityFile', models.FileField(max_length=500, upload_to=Instructors.models.fileUploadPath)),
                ('activityFileName', models.CharField(default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latest', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Activities', verbose_name='the related activity')),
                ('activityFileCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
