# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0070_remove_questionsskills_challengeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsskills',
            name='courseID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='courses'),
        ),
    ]
