# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0072_auto_20180126_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedactivityfiles',
            name='ID',
        ),
        migrations.AddField(
            model_name='uploadedactivityfiles',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
