# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0073_auto_20180126_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedactivityfiles',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedactivityfiles',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
