# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0074_auto_20180126_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challengePosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activities',
            name='uploadAttempts',
            field=models.IntegerField(default=0),
        ),
    ]
