# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0077_fill_in_challenge_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='manuallyGradedScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='number of possible points for a manually graded part of the challenge'),
        ),
    ]
