# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0078_challenges_manuallygradedscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='isGraded',
            field=models.BooleanField(default=False, verbose_name='Activity points will be added to the course grade'),
        ),
    ]
