# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0079_activities_isgraded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='points',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='challengesquestions',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
