# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-20 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0080_auto_20180413_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='deadLine',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
