# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0084_auto_20180509_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='isRandomized',
            field=models.BooleanField(default=False),
        ),
    ]
