# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-16 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0085_challenges_israndomized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='user',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
