# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-16 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0086_auto_20180816_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course'),
        ),
        migrations.AlterField(
            model_name='uploadedactivityfiles',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Activities', verbose_name='the related activity'),
        ),
        migrations.AlterField(
            model_name='uploadedactivityfiles',
            name='activityFileCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='uploadedFileCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
