# Generated by Django 2.0.8 on 2018-08-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0087_auto_20180816_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.ActivitiesCategory', verbose_name='Activities Category'),
        ),
        migrations.AlterField(
            model_name='questionsskills',
            name='courseID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='courses'),
        ),
    ]
