# Generated by Django 2.0.8 on 2018-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0089_activities_activityposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
