# Generated by Django 2.0.8 on 2018-12-18 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0090_challenges_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='dueDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
