# Generated by Django 2.0.8 on 2018-12-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0091_auto_20181218_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStreak',
            fields=[
                ('attendanceStreakID', models.AutoField(primary_key=True, serialize=False)),
                ('streakLength', models.IntegerField(default=0)),
                ('daysofWeek', models.CharField(max_length=75)),
                ('daysDeselected', models.CharField(max_length=20000)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
    ]
