# Generated by Django 2.0.8 on 2019-01-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0092_attendancestreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestreak',
            name='virtualCurrencyAwarded',
            field=models.IntegerField(default=0),
        ),
    ]
