# Generated by Django 2.0.8 on 2019-01-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0093_attendancestreak_virtualcurrencyawarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestreak',
            name='virtualCurrencyAwarded',
        ),
    ]
