# Generated by Django 2.0.8 on 2019-01-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0094_remove_attendancestreak_virtualcurrencyawarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakConfiguration',
            fields=[
                ('streakConfigurationID', models.AutoField(primary_key=True, serialize=False)),
                ('daysofWeek', models.CharField(max_length=75)),
                ('daysDeselected', models.CharField(max_length=20000)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
        migrations.CreateModel(
            name='Streaks',
            fields=[
                ('streakID', models.AutoField(primary_key=True, serialize=False)),
                ('streakType', models.IntegerField(default=0)),
                ('awardType', models.IntegerField(default=0)),
                ('streakLength', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancestreak',
            name='courseID',
        ),
        migrations.DeleteModel(
            name='AttendanceStreak',
        ),
    ]
