# Generated by Django 2.0.8 on 2019-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0095_auto_20190119_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='resetStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streaks',
            name='streakDescription',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streaks',
            name='vcAwardAmount',
            field=models.IntegerField(default=0),
        ),
    ]
