# Generated by Django 2.0.8 on 2019-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0096_auto_20190121_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='awardID',
            field=models.IntegerField(default=0),
        ),
    ]
