# Generated by Django 2.0.8 on 2019-01-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0097_streaks_awardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='periodicTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='the periodic task'),
        ),
    ]
