# Generated by Django 2.0.8 on 2019-01-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0098_streaks_periodictask'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='periodicVariable',
            field=models.IntegerField(default=0),
        ),
    ]
