# Generated by Django 2.0.8 on 2019-01-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0099_streaks_periodicvariable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streakconfiguration',
            old_name='daysofWeek',
            new_name='daysofClass',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='awardID',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='awardType',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='periodicTask',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='periodicVariable',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='streakDescription',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='vcAwardAmount',
        ),
        migrations.AlterField(
            model_name='streakconfiguration',
            name='daysDeselected',
            field=models.CharField(default='NONE', max_length=20000),
        ),
    ]
