# Generated by Django 2.0.8 on 2019-01-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0100_auto_20190123_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceStreakConfiguration',
            fields=[
                ('streakConfigurationID', models.AutoField(primary_key=True, serialize=False)),
                ('daysofClass', models.CharField(max_length=75)),
                ('daysDeselected', models.CharField(default='NONE', max_length=20000)),
                ('streakLength', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
        migrations.RemoveField(
            model_name='streakconfiguration',
            name='courseID',
        ),
        migrations.DeleteModel(
            name='StreakConfiguration',
        ),
    ]
