# Generated by Django 2.0.8 on 2019-01-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0101_auto_20190123_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaks',
            name='resetStreak',
        ),
        migrations.RemoveField(
            model_name='streaks',
            name='streakLength',
        ),
        migrations.AlterField(
            model_name='attendacestreakconfiguration',
            name='daysDeselected',
            field=models.CharField(max_length=20000),
        ),
    ]
