# Generated by Django 2.1.2 on 2019-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimages',
            name='imageFileName',
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='imageFile',
            field=models.FileField(max_length=500, upload_to='images/uploadedInstructorImages'),
        ),
    ]
