# Generated by Django 2.1.2 on 2019-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0105_auto_20190604_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetextparts',
            name='pointsInPart',
            field=models.IntegerField(default=1, verbose_name='Points in this Part'),
        ),
    ]
