# Generated by Django 2.1.2 on 2019-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0106_templatetextparts_pointsinpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestions',
            name='resubmissionPenalty',
            field=models.IntegerField(default=10, verbose_name='Resubmission penalty as an integer percentage'),
        ),
        migrations.AddField(
            model_name='dynamicquestions',
            name='submissionsAllowed',
            field=models.IntegerField(default=1, verbose_name='Number of Submissions Allowed'),
        ),
    ]
