# Generated by Django 2.1.2 on 2019-10-25 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0108_auto_20190827_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardGroup',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardGroupCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabilityDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('groupPos', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course Name')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.FlashCardGroup', verbose_name='Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCards',
            fields=[
                ('flashID', models.AutoField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=5000)),
                ('back', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.FlashCards')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.FlashCardGroup')),
            ],
        ),
    ]
