# Generated by Django 2.0.8 on 2019-10-29 20:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instructors', '0109_questionporgrammingfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionPorgrammingFiles',
            new_name='QuestionProgrammingFiles',
        ),
    ]
