# Generated by Django 2.0.8 on 2020-02-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0110_auto_20191029_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('universityID', models.AutoField(primary_key=True, serialize=False)),
                ('universityName', models.CharField(max_length=300)),
                ('universityDescription', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourses',
            fields=[
                ('universityCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='Course')),
                ('universityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Universities', verbose_name='Univerity')),
            ],
        ),
    ]
