# Generated by Django 2.0.8 on 2020-02-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0111_universities_universitycourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourses',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='universityID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Universities', verbose_name='Univerity'),
        ),
    ]
