# Generated by Django 2.2.4 on 2020-02-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0112_auto_20200218_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiescategory',
            name='xpWeight',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
