# Generated by Django 2.0.8 on 2020-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0114_auto_20200302_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiescategory',
            name='catPosition',
            field=models.IntegerField(default=0),
        ),
    ]
