# Generated by Django 2.2.4 on 2020-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0115_activitiescategory_catposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='universityTimezone',
            field=models.CharField(default='America/New_York', max_length=100),
        ),
    ]
