# Generated by Django 2.2.5 on 2020-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0116_universities_universitytimezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='basicHint',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='strongHint',
            field=models.CharField(default='', max_length=100),
        ),
    ]
