# Generated by Django 2.1.2 on 2020-04-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0118_flashcardgroup_flashcardgroupcourse_flashcards_flashcardtogroup'),
        ('Instructors', '0118_setup_default_dates'),
    ]

    operations = [
    ]
