# Generated by Django 2.1.2 on 2020-04-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0118_questions_ishintused'),
        ('Instructors', '0119_merge_20200404_1627'),
    ]

    operations = [
    ]
