# Generated by Django 2.2.4 on 2020-04-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0120_merge_20200410_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
