# Generated by Django 2.2.4 on 2020-04-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0121_delete_goals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestones',
        ),
    ]
