# Generated by Django 2.2.4 on 2020-04-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0122_delete_milestones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesSubTopics',
        ),
    ]
