# Generated by Django 2.2.4 on 2020-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0123_delete_coursessubtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardgroupcourse',
            name='hasAvailabilityDate',
            field=models.BooleanField(default=False),
        )
        
    ]
