# Generated by Django 2.2.4 on 2020-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0124_auto_20200421_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardtogroup',
            name='flashID',
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='flashName',
            field=models.CharField(default='Flashcard', max_length=200),
        ),
    ]
