# Generated by Django 2.2.4 on 2020-04-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0125_auto_20200421_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardtogroup',
            name='flashID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.FlashCards'),
            preserve_default=False,
        ),
    ]
