# Generated by Django 2.2.4 on 2020-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0126_flashcardtogroup_flashid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardgroupcourse',
            name='hasAvailabilityDate',
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='flashName',
            field=models.CharField(default='Flashcard', max_length=500),
        ),
    ]
