# Generated by Django 2.2.4 on 2021-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0129_challenges_isteamchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='universityPostfix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
