# Generated by Django 2.1.2 on 2021-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0132_activities_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Donations',
            field=models.IntegerField(default=0),
        ),
    ]
