# Generated by Django 2.1.2 on 2021-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0133_courses_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Donations',
        ),
        migrations.AddField(
            model_name='instructorregisteredcourses',
            name='Donations',
            field=models.IntegerField(default=0),
        ),
    ]
