# Generated by Django 2.1.2 on 2021-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0134_auto_20210926_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorregisteredcourses',
            name='Donations',
            field=models.IntegerField(default=20),
        ),
    ]
