# Generated by Django 2.1.2 on 2021-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0137_auto_20211002_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
