# Generated by Django 2.1.2 on 2021-10-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0138_auto_20211002_2232'),
        ('Instructors', '0137_auto_20211002_2324'),
    ]

    operations = [
    ]
