# Generated by Django 2.1.2 on 2021-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0138_auto_20211014_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='allowRichTextSubmission',
            field=models.BooleanField(default=False),
        ),
    ]
