# Generated by Django 2.1.15 on 2021-10-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0139_activities_allowrichtextsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='basicHint',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='instructorNotes',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='preview',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='strongHint',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
