# Generated by Django 2.1.2 on 2021-12-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0140_auto_20211021_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('triviaID', models.AutoField(primary_key=True, serialize=False)),
                ('triviaName', models.CharField(max_length=500)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='Registered Course')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('challengeQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.ChallengesQuestions', verbose_name='Linked Trivia Question')),
                ('triviaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Trivia', verbose_name='Linked Trivia Session')),
            ],
        ),
    ]
