# Generated by Django 2.1.2 on 2021-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0141_trivia_triviaquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='maximumPointsPossible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='maximumVCPossible',
            field=models.IntegerField(default=0),
        ),
    ]
