# Generated by Django 2.2.4 on 2022-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0143_auto_20211201_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='currentlyRunning',
            field=models.BooleanField(default=False, verbose_name='Current running status of trivia'),
        ),
    ]
