# Generated by Django 2.2.4 on 2022-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0145_auto_20220921_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='questionType',
            field=models.CharField(default='MC', max_length=2),
        ),
    ]
