# Generated by Django 2.1.2 on 2022-11-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0147_triviaquestion_questionposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='timePressure',
            field=models.BooleanField(default=False),
        ),
    ]
