# Generated by Django 2.2.4 on 2022-10-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instructors', '0147_triviaquestion_questionposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaSession',
            fields=[
                ('trivia_id', models.AutoField(primary_key=True, serialize=False)),
                ('trivia_name', models.CharField(max_length=100)),
                ('trivia_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Trivia')),
            ],
        ),
    ]
