# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0003_auto_20151029_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionarguments',
            name='sequenceNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='badges',
            name='assignToChallenges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operand1Type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operand1Value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operand2Type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operand2Value',
            field=models.IntegerField(),
        ),
    ]
