# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0010_auto_20161026_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(db_index=True, default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Rules')),
            ],
        ),
    ]
