# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 19:17
from __future__ import unicode_literals

from django.db import migrations

def copy_events(apps,schema_editor):
    Rules = apps.get_model("Badges","Rules")
    RuleEvents = apps.get_model("Badges","RuleEvents")
    for rule in Rules.objects.all():
        ruleEvent = RuleEvents()
        ruleEvent.rule = rule
        ruleEvent.event = rule.eventID
        ruleEvent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0011_ruleevents'),
    ]

    operations = [
        migrations.RunPython(copy_events)
    ]
