# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0012_auto_20161221_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='eventID',
        ),
    ]
