# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0013_remove_rules_eventid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseconfigparams',
            old_name='leaderBoardUpdateFreq',
            new_name='leaderboardUpdateFreq',
        ),
        migrations.RenameField(
            model_name='courseconfigparams',
            old_name='numStudentToppersDisplayed',
            new_name='numBadgesDisplayed',
        ),
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='classRankingDisplayed',
        ),
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='studCanChangeClassRankingVis',
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='numStudentDisplayed',
            field=models.IntegerField(default=0),
        ),
    ]
