# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0014_auto_20170120_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseconfigparams',
            old_name='numStudentDisplayed',
            new_name='numStudentsDisplayed',
        ),
    ]
