# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0015_auto_20170120_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgechallenges',
            name='badgeID',
        ),
        migrations.RemoveField(
            model_name='badgechallenges',
            name='challengeID',
        ),
        migrations.DeleteModel(
            name='BadgeChallenges',
        ),
    ]
