# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0040_auto_20170322_1748'),
        ('Badges', '0016_auto_20170212_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCurrencyRules',
            fields=[
                ('vcRuleID', models.AutoField(primary_key=True, serialize=False)),
                ('vcRuleName', models.CharField(max_length=30)),
                ('vcRuleDescription', models.CharField(max_length=100)),
                ('vcAmount', models.IntegerField(default=0)),
                ('assignToChallenges', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('ruleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Rules', verbose_name='the related rule')),
            ],
        ),
    ]
