# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0018_auto_20170322_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='vcAmount',
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleType',
            field=models.BooleanField(default=True),
        ),
    ]
