# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0019_auto_20170324_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='thresholdToLevelDifficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='thresholdToLevelMedium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpWeightAPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpWeightSChallenge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpWeightSP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpWeightWChallenge',
            field=models.IntegerField(default=0),
        ),
    ]
