# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0020_auto_20170404_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='virtualCurrencyAdded',
            field=models.IntegerField(default=0),
        ),
    ]
