# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0021_courseconfigparams_virtualcurrencyadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='gamificationUsed',
            field=models.BooleanField(default=False),
        ),
    ]
