# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0021_courseconfigparams_virtualcurrencyadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Activities', verbose_name='the activity included in the set')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition this set goes with')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Challenges', verbose_name='the challenge included in the set')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition this set goes with')),
            ],
        ),
    ]
