# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0054_uploadedfiles'),
        ('Badges', '0022_activityset_challengeset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='conditions',
            name='courseID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='The course this condition belongs to'),
        ),
        migrations.AddField(
            model_name='conditionset',
            name='conditionInSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition which is part of this set'),
        ),
        migrations.AddField(
            model_name='conditionset',
            name='parentCondition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentCondition', to='Badges.Conditions', verbose_name='the condition this set goes with'),
        ),
    ]
