# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0023_auto_20170712_0623'),
        ('Badges', '0022_courseconfigparams_gamificationused'),
    ]

    operations = [
    ]
