# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-10 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0065_auto_20171110_2109'),
        ('Badges', '0024_merge_20170802_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition this set goes with')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Topics', verbose_name='the topic included in the set')),
            ],
        ),
    ]
