# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0028_auto_20180118_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcRuleType',
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleType',
            field=models.BooleanField(default=True),
        ),
    ]
