# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0070_remove_questionsskills_challengeid'),
        ('Badges', '0029_auto_20180118_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='virtualcurrencycustomruleinfo_ptr',
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='courseID',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleDescription',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleName',
            field=models.CharField(default='n', max_length=30),
            preserve_default=False,
        ),
    ]
