# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0031_virtualcurrencycustomruleinfo_vcruletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleDescription',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleID',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleName',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='vcRuleType',
        ),
        migrations.AddField(
            model_name='virtualcurrencyruleinfo',
            name='virtualcurrencycustomruleinfo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Badges.VirtualCurrencyCustomRuleInfo'),
            preserve_default=False,
        ),
    ]
