# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-19 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0032_auto_20180118_1901'),
        ('Badges', '0029_virtualcurrencyruleinfo_awardfrequency'),
    ]

    operations = [
    ]
