# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-21 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0033_merge_20180119_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcurrencyruleinfo',
            name='ruleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule'),
        ),
    ]
