# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0034_auto_20180121_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcRuleDescription',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcRuleName',
            field=models.CharField(max_length=300),
        ),
    ]
