# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0035_auto_20180122_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='badgeDescription',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='badges',
            name='badgeImage',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='badges',
            name='badgeName',
            field=models.CharField(max_length=300),
        ),
    ]
