# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0036_auto_20180123_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionarguments',
            name='ruleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule'),
        ),
        migrations.AlterField(
            model_name='badges',
            name='ruleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='conditionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Conditions', verbose_name='the related condition'),
        ),
        migrations.AlterField(
            model_name='virtualcurrencyruleinfo',
            name='ruleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule'),
        ),
    ]
