# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0084_auto_20180509_1624'),
        ('Badges', '0037_auto_20180123_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesInfo',
            fields=[
                ('badgeID', models.AutoField(primary_key=True, serialize=False)),
                ('badgeName', models.CharField(max_length=300)),
                ('badgeDescription', models.CharField(max_length=10000)),
                ('badgeImage', models.CharField(max_length=300)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
    ]
