# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0084_auto_20180509_1624'),
        ('Badges', '0039_auto_20180514_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategorySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.ActivitiesCategory', verbose_name='the category included in the set')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition this set goes with')),
            ],
        ),
    ]
