# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0038_badgesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcRuleLimit',
            field=models.IntegerField(default=0),
        ),
    ]
