# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0040_activitycategoryset'),
        ('Badges', '0040_virtualcurrencycustomruleinfo_vcrulelimit'),
    ]

    operations = [
    ]
