# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0041_auto_20180516_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgesinfo',
            name='courseID',
        ),
        migrations.DeleteModel(
            name='BadgesInfo',
        ),
    ]
