# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('Badges', '0042_auto_20180516_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badges',
            new_name='BadgesInfo',
        ),
    ]
