# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0043_auto_20180516_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('badgesinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Badges.BadgesInfo')),
                ('futureRuleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule')),
            ],
            bases=('Badges.badgesinfo',),
        ),
        migrations.RemoveField(
            model_name='badgesinfo',
            name='assignToChallenges',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='assignToChallenges',
        ),
    ]
