# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0045_copy_badgeInfo_rules_to_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgesinfo',
            name='ruleID',
        ),
    ]
