# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0047_auto_20180516_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesinfo',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
