# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-22 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0041_merge_20180516_1629'),
        ('Badges', '0048_badgesinfo_manual'),
    ]

    operations = [
    ]
