# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0049_merge_20180522_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='courseAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
