# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-12 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0051_auto_20180611_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcurrencyruleinfo',
            name='awardFrequency',
        ),
    ]
