# Generated by Django 2.0.8 on 2018-09-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0053_ruleevents_inglobalcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicBadges',
            fields=[
                ('badgesinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Badges.BadgesInfo')),
                ('periodicVariableID', models.IntegerField()),
                ('timePeriodID', models.IntegerField()),
                ('numberOfAwards', models.IntegerField(default=1)),
            ],
            bases=('Badges.badgesinfo',),
        ),
        migrations.CreateModel(
            name='VirtualCurrencyPeriodicRule',
            fields=[
                ('virtualcurrencycustomruleinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Badges.VirtualCurrencyCustomRuleInfo')),
                ('periodicVariableID', models.IntegerField()),
                ('timePeriodID', models.IntegerField()),
                ('numberOfAwards', models.IntegerField(default=1)),
            ],
            bases=('Badges.virtualcurrencycustomruleinfo',),
        ),
        migrations.AddField(
            model_name='badgesinfo',
            name='isPeriodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualcurrencycustomruleinfo',
            name='isPeriodic',
            field=models.BooleanField(default=False),
        ),
    ]
