# Generated by Django 2.0.8 on 2018-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0054_auto_20180905_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesinfo',
            name='badgePostion',
            field=models.IntegerField(default=0),
        ),
    ]
