# Generated by Django 2.0.8 on 2018-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0054_auto_20180905_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicbadges',
            name='isRandom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodicbadges',
            name='operatorType',
            field=models.CharField(default='=', max_length=2),
        ),
        migrations.AddField(
            model_name='periodicbadges',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='isRandom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='operatorType',
            field=models.CharField(default='=', max_length=2),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
    ]
