# Generated by Django 2.0.8 on 2018-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0055_badgesinfo_badgepostion'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcRulePostion',
            field=models.IntegerField(default=0),
        ),
    ]
