# Generated by Django 2.0.8 on 2018-09-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0055_auto_20180913_1028'),
        ('Badges', '0056_virtualcurrencycustomruleinfo_vcrulepostion'),
    ]

    operations = [
    ]
