# Generated by Django 2.0.8 on 2018-09-22 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0057_merge_20180918_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicbadges',
            name='lastModified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='periodicbadges',
            name='periodicType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='lastModified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='periodicType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='periodicbadges',
            name='isRandom',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodicbadges',
            name='numberOfAwards',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='virtualcurrencyperiodicrule',
            name='isRandom',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='virtualcurrencyperiodicrule',
            name='numberOfAwards',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
