# Generated by Django 2.0.8 on 2018-09-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0058_auto_20180922_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgesinfo',
            old_name='badgePostion',
            new_name='badgePosition',
        ),
        migrations.RenameField(
            model_name='virtualcurrencycustomruleinfo',
            old_name='vcRulePostion',
            new_name='vcRulePosition',
        ),
    ]
