# Generated by Django 2.0.8 on 2018-10-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0088_auto_20180817_1639'),
        ('Badges', '0059_auto_20180922_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardsConfig',
            fields=[
                ('leaderboardID', models.AutoField(primary_key=True, serialize=False)),
                ('leaderboardName', models.CharField(max_length=300)),
                ('leaderboardDescription', models.CharField(max_length=10000)),
                ('leaderboardUsed', models.BooleanField(default=False)),
                ('numStudentsDisplayed', models.IntegerField(default=0)),
                ('timePeriodUpdateInterval', models.IntegerField()),
                ('leaderboardDisplayPage', models.BooleanField(default=False)),
                ('studCanChangeLeaderboardVis', models.BooleanField(default=False)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
    ]
