# Generated by Django 2.0.8 on 2018-11-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0088_auto_20180817_1639'),
        ('Badges', '0059_auto_20180922_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressiveUnlocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=10000)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('ruleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.Rules', verbose_name='the related rule')),
            ],
        ),
    ]
