# Generated by Django 2.0.8 on 2018-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0060_leaderboardsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardsconfig',
            name='timePeriodUpdateInterval',
            field=models.IntegerField(default=1500),
        ),
    ]
