# Generated by Django 2.0.8 on 2018-10-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0061_auto_20181001_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicbadges',
            name='periodicTask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='the periodic task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='periodicTask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='the periodic task'),
            preserve_default=False,
        ),
    ]
