# Generated by Django 2.0.8 on 2018-10-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0061_auto_20181001_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardsconfig',
            name='periodicVariable',
            field=models.IntegerField(default=0),
        ),
    ]
