# Generated by Django 2.0.8 on 2018-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0061_auto_20181102_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressiveunlocking',
            name='description',
            field=models.CharField(default='Sorry its locked', max_length=10000),
        ),
    ]
