# Generated by Django 2.0.8 on 2018-12-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0063_auto_20181011_1316'),
        ('Badges', '0062_auto_20181102_0350'),
    ]

    operations = [
    ]
