# Generated by Django 2.0.8 on 2018-10-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0062_leaderboardsconfig_periodicvariable'),
        ('Badges', '0063_auto_20181011_1316'),
    ]

    operations = [
    ]
