# Generated by Django 2.0.8 on 2018-12-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0064_merge_20181221_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressiveunlocking',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
