# Generated by Django 2.0.8 on 2018-10-18 21:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0008_auto_20180914_1922'),
        ('Badges', '0064_merge_20181018_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardsconfig',
            name='lastModified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leaderboardsconfig',
            name='periodicTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='the periodic task'),
        ),
    ]
