# Generated by Django 2.0.8 on 2018-11-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0065_auto_20181018_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardsconfig',
            old_name='leaderboardUsed',
            new_name='isContinous',
        ),
    ]
