# Generated by Django 2.0.8 on 2019-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0065_auto_20181221_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='classmatesChallenges',
            field=models.BooleanField(default=False),
        ),
    ]
