# Generated by Django 2.0.8 on 2019-01-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0065_auto_20181221_1715'),
        ('Badges', '0064_courseconfigparams_streaksused'),
    ]

    operations = [
    ]
