# Generated by Django 2.0.8 on 2019-01-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0066_merge_20190119_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicbadges',
            name='streakLength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='resetStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='streakLength',
            field=models.IntegerField(default=0),
        ),
    ]
