# Generated by Django 2.0.8 on 2018-11-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0066_auto_20181107_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardsconfig',
            name='isXpTable',
            field=models.BooleanField(default=False),
        ),
    ]
