# Generated by Django 2.0.8 on 2019-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0066_courseconfigparams_progressbarused'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='seriousChallengesGrouped',
            field=models.BooleanField(default=False),
        ),
    ]
