# Generated by Django 2.0.8 on 2018-11-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0067_leaderboardsconfig_isxptable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardsconfig',
            old_name='isXpTable',
            new_name='isXpLeaderboard',
        ),
        migrations.RemoveField(
            model_name='leaderboardsconfig',
            name='studCanChangeLeaderboardVis',
        ),
    ]
