# Generated by Django 2.0.8 on 2019-01-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0067_auto_20190121_1602'),
        ('Badges', '0067_courseconfigparams_seriouschallengesgrouped'),
    ]

    operations = [
    ]
