# Generated by Django 2.0.8 on 2019-02-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0091_auto_20181218_1444'),
        ('Badges', '0067_courseconfigparams_seriouschallengesgrouped'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceStreakConfiguration',
            fields=[
                ('streakConfigurationID', models.AutoField(primary_key=True, serialize=False)),
                ('daysofClass', models.CharField(max_length=75)),
                ('daysDeselected', models.CharField(max_length=20000)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='streaksUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodicbadges',
            name='resetStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualcurrencyperiodicrule',
            name='resetStreak',
            field=models.BooleanField(default=False),
        ),
    ]
