# Generated by Django 2.0.8 on 2019-01-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0068_periodicbadges_resetstreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicbadges',
            name='resetStreak',
        ),
        migrations.RemoveField(
            model_name='periodicbadges',
            name='streakLength',
        ),
        migrations.RemoveField(
            model_name='virtualcurrencyperiodicrule',
            name='streakLength',
        ),
    ]
