# Generated by Django 2.0.8 on 2019-01-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0068_merge_20190128_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='chatUsed',
            field=models.BooleanField(default=True),
        ),
    ]
