# Generated by Django 2.0.8 on 2019-02-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0068_merge_20190128_1553'),
        ('Badges', '0068_auto_20190204_1507'),
    ]

    operations = [
    ]
