# Generated by Django 2.1.2 on 2019-02-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0069_merge_20190204_1514'),
        ('Badges', '0069_courseconfigparams_chatused'),
    ]

    operations = [
    ]
