# Generated by Django 2.0.8 on 2018-11-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0069_auto_20181114_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardsconfig',
            old_name='continousHowFarBack',
            new_name='howFarBack',
        ),
    ]
