# Generated by Django 2.0.8 on 2018-11-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0070_auto_20181115_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardsconfig',
            old_name='leaderboardDisplayPage',
            new_name='displayOnCourseHomePage',
        ),
    ]
