# Generated by Django 2.0.8 on 2019-01-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0067_courseconfigparams_seriouschallengesgrouped'),
        ('Badges', '0070_periodicbadges_resetstreak'),
    ]

    operations = [
    ]
