# Generated by Django 2.0.8 on 2019-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0071_merge_20190127_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='streaksUsed',
            field=models.BooleanField(),
        ),
    ]
