# Generated by Django 2.0.8 on 2019-02-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0071_auto_20181115_2055'),
        ('Badges', '0065_auto_20181221_1715'),
    ]

    operations = [
    ]
