# Generated by Django 2.0.8 on 2019-02-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0069_courseconfigparams_chatused'),
        ('Badges', '0069_merge_20190204_1514'),
        ('Badges', '0072_merge_20190204_1612'),
    ]

    operations = [
    ]
