# Generated by Django 2.0.8 on 2019-01-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0072_auto_20190127_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='streaksUsed',
            field=models.BooleanField(default=True),
        ),
    ]
