# Generated by Django 2.1.2 on 2019-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0073_merge_20190208_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='betVC',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='vcDuelParticipants',
            field=models.IntegerField(default=0),
        ),
    ]
