# Generated by Django 2.0.8 on 2019-02-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0074_remove_courseconfigparams_chatused'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='chatUsed',
            field=models.BooleanField(default=True),
        ),
    ]
