# Generated by Django 2.0.8 on 2019-01-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0104_auto_20190128_2201'),
        ('Badges', '0074_auto_20190127_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceStreakConfiguration',
            fields=[
                ('streakConfigurationID', models.AutoField(primary_key=True, serialize=False)),
                ('daysofClass', models.CharField(max_length=75)),
                ('daysDeselected', models.CharField(max_length=20000)),
                ('streakLength', models.IntegerField(default=0)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
                ('periodicVC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Badges.VirtualCurrencyPeriodicRule', verbose_name='the related course')),
            ],
        ),
    ]
