# Generated by Django 2.0.8 on 2019-01-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0008_auto_20180914_1922'),
        ('Badges', '0075_attendacestreakconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendacestreakconfiguration',
            name='periodicVC',
        ),
        migrations.AddField(
            model_name='attendacestreakconfiguration',
            name='periodicTask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask', verbose_name='periodicVC'),
        ),
    ]
