# Generated by Django 2.0.8 on 2019-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0075_courseconfigparams_chatused'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpCalculateSeriousByMaxScore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='xpCalculateWarmupByMaxScore',
            field=models.BooleanField(default=False),
        ),
    ]
