# Generated by Django 2.1.2 on 2019-02-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0076_auto_20190219_1709'),
        ('Badges', '0074_auto_20190218_2220'),
    ]

    operations = [
    ]
