# Generated by Django 2.0.8 on 2019-01-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0076_auto_20190128_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendacestreakconfiguration',
            name='periodicTask',
        ),
        migrations.RemoveField(
            model_name='attendacestreakconfiguration',
            name='streakLength',
        ),
    ]
