# Generated by Django 2.1.2 on 2019-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0077_merge_20190222_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='vcDuelMaxBet',
            field=models.IntegerField(default=3),
        ),
    ]
