# Generated by Django 2.1.2 on 2019-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0078_courseconfigparams_vcduelmaxbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='studCanChangeGoal',
            field=models.BooleanField(default=True),
        ),
    ]
