# Generated by Django 2.1.2 on 2019-04-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0079_auto_20190328_1205'),
        ('Badges', '0079_courseconfigparams_studcanchangegoal'),
    ]

    operations = [
    ]
