# Generated by Django 2.1.2 on 2019-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0080_merge_20190409_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicbadges',
            name='threshold',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
