# Generated by Django 2.1.2 on 2019-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0081_auto_20190823_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcurrencycustomruleinfo',
            name='vcAmountVaries',
            field=models.BooleanField(default=False),
        ),
    ]
