# Generated by Django 2.2.4 on 2019-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0081_auto_20190823_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcurrencyperiodicrule',
            name='threshold',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
