# Generated by Django 2.0.8 on 2019-09-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0082_auto_20190905_1736'),
        ('Badges', '0082_virtualcurrencycustomruleinfo_vcamountvaries'),
    ]

    operations = [
    ]
