# Generated by Django 2.2.5 on 2019-09-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0082_auto_20190905_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='debugSystemVariablesDisplayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='gamificationDisplayed',
            field=models.BooleanField(default=False),
        ),
    ]
