# Generated by Django 2.2.5 on 2019-09-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0083_auto_20190915_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseconfigparams',
            old_name='gamificationDisplayed',
            new_name='contentUnlockingDisplayed',
        ),
    ]
