# Generated by Django 2.2.5 on 2019-10-06 01:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0108_auto_20190827_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students', '0086_auto_20190822_1509'),
        ('Badges', '0084_auto_20190920_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesVCLog',
            fields=[
                ('badgesVCLogID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studentBadges', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.StudentBadges')),
                ('studentVirtualCurrency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.StudentVirtualCurrencyRuleBased')),
            ],
        ),
    ]
