# Generated by Django 2.1.2 on 2020-01-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0088_auto_20200111_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='gradebookUsed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='seriousChallengesUsed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='warmupsUsed',
            field=models.BooleanField(default=True),
        ),
    ]
