# Generated by Django 2.1.2 on 2020-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0088_auto_20200111_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=200)),
                ('sequence', models.IntegerField()),
            ],
        ),
    ]
