# Generated by Django 2.1.2 on 2020-01-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0089_celerytestresult'),
        ('Badges', '0089_auto_20200130_1435'),
    ]

    operations = [
    ]
