# Generated by Django 2.0.8 on 2020-02-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0090_merge_20200130_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='calloutAfterWarmup',
            field=models.BooleanField(default=True),
        ),
    ]
