# Generated by Django 2.2.4 on 2020-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0091_courseconfigparams_calloutafterwarmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='displayStudentStartPageSummary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='progressBarTotalPoints',
            field=models.IntegerField(default=100),
        ),
    ]
