# Generated by Django 2.2.4 on 2020-02-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0092_courseconfigparams_progressbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='progressBarGroupAverage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='progressBarGroupUsed',
            field=models.BooleanField(default=False),
        ),
    ]
