# Generated by Django 2.1.2 on 2020-02-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0093_auto_20200211_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='activitiesUsed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='announcementsUsed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='skillsUsed',
            field=models.BooleanField(default=False),
        ),
    ]
