# Generated by Django 2.2.5 on 2020-02-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0098_refactor_badgevclog_part3'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='skillLeaderboardDisplayed',
            field=models.BooleanField(default=False),
        ),
    ]
