# Generated by Django 2.2.4 on 2020-03-02 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0099_courseconfigparams_skillleaderboarddisplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgesvclog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaderboardsconfig',
            name='lastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='periodicbadges',
            name='lastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='virtualcurrencyperiodicrule',
            name='lastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
