# Generated by Django 2.2.4 on 2020-03-04 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0100_auto_20200302_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytasklog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The last time the celery task has run completely and was recorded', verbose_name='Task Timestamp'),
        ),
    ]
