# Generated by Django 2.2.5 on 2020-03-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0101_timezone_default_celery_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='customLeaderboardsUsed',
            field=models.BooleanField(default=False),
        ),
    ]
