# Generated by Django 2.2.4 on 2020-04-04 05:35

from django.db import migrations, models
import datetime

def migrate_course_dates(apps, schema_editor):
    # Update the course config "has date" parameters 

    CourseConfigParams = apps.get_model("Badges","CourseConfigParams")

    default_date_year = datetime.datetime.strptime("12/31/2999 11:59 PM", "%m/%d/%Y %I:%M %p").replace(tzinfo=datetime.timezone.utc).year
    
    config_params = CourseConfigParams.objects.all()
    for params in config_params:
        save = False
        # This datetimefield is assume to not be a default datetime since the year is < 2999
        if params.courseStartDate.year < default_date_year:
            params.hasCourseStartDate = True
            save = True

        if params.courseEndDate.year < default_date_year:
            params.hasCourseEndDate = True
            save = True

        if save:
            params.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0104_auto_20200330_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='hasCourseEndDate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='hasCourseStartDate',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_course_dates),
    ]
