# Generated by Django 2.0.8 on 2020-04-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0106_courseconfigparams_goalsused'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='levelTo1XP',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=100),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='nextLevelPercent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=100),
        ),
    ]
