# Generated by Django 2.2.4 on 2020-11-09 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0110_auto_20201019_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='teamsLockInDeadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 11, 7, 19, tzinfo=utc), verbose_name='Deadline for team members to be locked in to the team'),
        ),
    ]
