# Generated by Django 2.2.4 on 2020-11-22 02:26

import Badges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0111_auto_20201109_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='teamsLockInDeadline',
            field=models.DateTimeField(default=Badges.models.custom_now, verbose_name='Deadline for team members to be locked in to the team'),
        ),
    ]
