# Generated by Django 2.1.15 on 2021-02-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0129_challenges_isteamchallenge'),
        ('Badges', '0114_auto_20210104_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Badges.Conditions', verbose_name='the condition this set goes with')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Skills', verbose_name='the skill included in the set')),
            ],
        ),
    ]
