# Generated by Django 2.1.15 on 2021-06-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0132_activities_isavailable'),
        ('Badges', '0115_skillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='The name of the type of player')),
                ('badgesUsed', models.BooleanField(default=False)),
                ('levelingUsed', models.BooleanField(default=False)),
                ('classmatesChallenges', models.BooleanField(default=False)),
                ('betVC', models.BooleanField(default=False)),
                ('progressBarUsed', models.BooleanField(default=False)),
                ('displayStudentStartPageSummary', models.BooleanField(default=False)),
                ('displayAchievementPage', models.BooleanField(default=False)),
                ('leaderboardUsed', models.BooleanField(default=False)),
                ('virtualCurrencyUsed', models.BooleanField(default=False)),
                ('goalsUsed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instructors.Courses', verbose_name='the related course')),
            ],
        ),
    ]
