# Generated by Django 2.1.2 on 2021-06-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0116_playertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='adaptationUsed',
            field=models.BooleanField(default=False, verbose_name='Allows or disallows the use of Player-Types in the course.'),
        ),
    ]
