# Generated by Django 2.1.2 on 2022-01-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0120_courseconfigparams_classfundenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='triviaEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
