# Generated by Django 2.1.2 on 2022-04-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0120_courseconfigparams_classfundenabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='thresholdToLevelDifficulty',
        ),
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='thresholdToLevelMedium',
        ),
    ]
