# Generated by Django 2.1.2 on 2022-03-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0124_rules_applauseoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='applauseOption',
        ),
    ]
