# Generated by Django 2.1.2 on 2022-04-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0125_remove_rules_applauseoption'),
    ]

   # operations = [
   #     migrations.AddField(
   #         model_name='virtualapplausecustomruleinfo',
   #         name='ApplauseOption',
   #         field=models.IntegerField(default=1200),
   #     ),
   # ]
