# Generated by Django 2.1.2 on 2022-04-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0127_virtualapplauseruleinfoo'),
    ]

   # operations = [
   ##     migrations.RemoveField(
   ##         model_name='virtualapplausecustomruleinfo',
    ##        name='courseID',
    ##    ),
      ##  migrations.RemoveField(
     ##       model_name='virtualapplauseruleinfo',
     ##       name='ruleID',
     ##   ),
     ##   migrations.RemoveField(
     ##       model_name='virtualapplauseruleinfo',
     ##       name='virtualapplausecustomruleinfo_ptr',
      ##  ),
  ##      migrations.DeleteModel(
   #         name='VirtualApplauseCustomRuleInfo',
   #     ),
    #    migrations.DeleteModel(
     #       name='VirtualApplauseRuleInfo',
     #   ),
    #]
