# Generated by Django 2.1.2 on 2022-05-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0121_auto_20220402_1709'),
        ('Badges', '0128_auto_20220421_0142'),
    ]

    operations = [
    ]
