# Generated by Django 2.1.2 on 2022-05-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0130_courseconfigparams_timepressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertype',
            name='timePressure',
            field=models.BooleanField(default=False),
        ),
    ]
