# Generated by Django 2.1.2 on 2022-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0131_playertype_timepressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
    ]
