# Generated by Django 2.1.2 on 2022-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

 
    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
    ]
