# Generated by Django 2.2.4 on 2022-09-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0131_playertype_timepressure'),
        ('Badges', '0121_courseconfigparams_triviaenabled'),
    ]

    operations = [
    ]
