# Generated by Django 2.2.4 on 2022-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0132_merge_20220930_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playertype',
            name='timePressure',
            field=models.BooleanField(default=True),
        ),
    ]
