# Generated by Django 2.2.4 on 2022-10-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0132_auto_20220921_1641'),
        ('Badges', '0121_courseconfigparams_triviaenabled'),
    ]

    operations = [
    ]
