# Generated by Django 2.2.4 on 2022-10-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0133_merge_20221005_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfigparams',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructors.Courses', verbose_name='the related course.'),
        ),
    ]
