# Generated by Django 2.1.2 on 2022-11-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0134_auto_20221005_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseconfigparams',
            name='timePressure',
        ),
    ]
