# Generated by Django 2.1.2 on 2022-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0135_remove_courseconfigparams_timepressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertype',
            name='timePressure',
        ),
        migrations.AddField(
            model_name='playertype',
            name='timePressureSerious',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertype',
            name='timePressureWarmup',
            field=models.BooleanField(default=False),
        ),
    ]
