# Generated by Django 2.1.2 on 2022-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badges', '0136_auto_20221123_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfigparams',
            name='timePressureSerious',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseconfigparams',
            name='timePressureWarmup',
            field=models.BooleanField(default=False),
        ),
    ]
